# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Hosted VS2017
  demands: DotNetFramework

steps:
- task: NodeTool@0
  displayName: 'Use Node 9.x'
  inputs:
    versionSpec: 9.x

- task: PowerShell@1
  displayName: 'PowerShell Script - CAKE'
  inputs:
    scriptName: build/build.ps1
    arguments: '-target Deploy -verbosity Diagnostic -ScriptArgs ''-NETLIFY_TOKEN="$(NETLIFY_TOKEN)"'',''-SITE_NAME="$(SITE_NAME)"'''
    failOnStandardError: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: output'
  inputs:
    PathtoPublish: 'src\output'
    ArtifactName: output
